"""Change drop_time from string to datetime

Revision ID: 2379185aad49
Revises: 85eaf9db5cc0
Create Date: 2025-08-05 16:42:07.435547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2379185aad49'
down_revision = '85eaf9db5cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sound_circle', schema=None) as batch_op:
        batch_op.alter_column('drop_time',
               existing_type=sa.String(),
               type_=sa.DateTime(),
               postgresql_using='drop_time::timestamp',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sound_circle', schema=None) as batch_op:
        batch_op.alter_column('drop_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
