"""Fix SongFeedback foreign key to point to Submission

Revision ID: a651e25ed961
Revises: b550f52aec32
Create Date: 2025-08-08 15:54:03.417939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a651e25ed961'
down_revision = 'b550f52aec32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['submission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'song_id', name='unique_user_song_feedback')
    )
    op.drop_table('feedback')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rater_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback_value', postgresql.ENUM('like', 'neutral', 'dislike', name='feedback_enum'), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rater_id'], ['user.id'], name=op.f('feedback_rater_id_fkey')),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], name=op.f('feedback_submission_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey')),
    sa.UniqueConstraint('submission_id', 'rater_id', name=op.f('unique_feedback'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('song_feedback')
    # ### end Alembic commands ###
